### ISSUE TITLE
one way failure

### ISSUE THREAD

**Issue by darren-henderson** [cuviper/ssh-pageant#26]
I'm unable to use ssh-add to add a key to pageant. I always get SSH_AGENT_FAILURE. However, if I add a key to pageant directly I am able to list the available keys with "ssh-add -l" and ssh is able to use it as it should. Just can't seem to add a key from inside a cygwin rxvt/bash session.

Using:
ssh-pageant 32 bit
Cygwin 32 bit synced today (2015-01-25)
Pageant 0.64 
Windows 7 64 bit

I've tried rebasing cygwin and reinstalling putty etc.

I use a similar combination of software on other installations and everything works fine. Any suggestions on tracking down the issue would be appreciated.

Thanks.

**Comment by darren-henderson** [comment]
Immediately after posting this I tried on more thing. I had been using an alias like

 alias sshhome='ssh-add -t 4h ~/.ssh/home.key'

So, tried by passing the alias I did

'ssh-add -t 4h ~/.ssh/home.key'  which fails as described. However doing 'ssh-add ~/.ssh/home.key' works as it should.

So, there is apparently an issue with using the -t option which I see is not meant to be supported anyhow.

**Comment by cuviper** [comment]
Well, ssh-pageant is not interpreting the messages in any way, except for reading their size from the first four bytes.  Otherwise it's just passing everything as-is to Pageant, and returning whatever Pageant says.  Note you'll get the exact same failure if you used PuTTY into any system and tried `ssh-add -t` -- Pageant just doesn't understand.

It might be possible for an internal timer to generate delete messages, as you suggest, but you also identified the problem with ssh-pageant exiting early (or even crashing).  And maybe I should turn `ssh-pageant -t` into an error instead of ignoring, but it does at least warn "option is not supported by Pageant -- t" unless you also used `-q` to silence it.

I think the best option is to get timeouts implemented in Pageant itself, per the wish [pageant-key-mgmt](http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/pageant-key-mgmt.html).  Last modified in 2002 though, so I wouldn't hold your breath.  Maybe they'd still take a code contribution for it.

If you'd like to submit an update to ssh-pageant's docs, I'll take it.

**Comment by darren-henderson** [comment]
I offered a change via GitHub. Just added a simple caveat to the man
page. Hopefully I did it correctly.

Thanks,

-Darren

**Comment by cuviper** [comment]
I committed your change, thanks!
