### ISSUE TITLE
Support for WSL bash

### ISSUE THREAD

**Issue by 131** [cuviper/ssh-pageant#52]
Since windows fall udpate (2017-11),  WSL can spawn windows binaries (yet use stdin/stdout & pipes).
Could you do an update so it can be used in WSL ?

(https://blogs.msdn.microsoft.com/commandline/2017/10/11/whats-new-in-wsl-in-windows-10-fall-creators-update/)

**Comment by cuviper** [comment]
The problem for ssh-pageant is that it wants to access unix sockets and the Windows API *in the same process*.  Once you get into spawning external processes, then you have arrived at the reason for the [weasel-pageant](https://github.com/vuori/weasel-pageant) fork.  I recommend you use that for WSL!

I don't intend to port that functionality back here, so I'm going to close this.  If someone can find a way to do it all in-process, I'd consider that, but otherwise WSL support is off the table here.
